services:
  runtime:
    image: chenjunn/rm_vision:lastest
    volumes:
      - ws:/ros_ws
    network_mode: "host"
    privileged: true
    # Available camera types: usb, mv, hik
    command: /bin/bash -c "source /ros_ws/install/setup.bash && \
      ros2 launch rm_vision_bringup vision_bringup.launch.py \
      camera_type:=usb \
      use_serial:=False "

  debug:
    image: chenjunn/rm_vision:lastest
    depends_on:
      - "runtime"
    volumes:
      - ws:/ros_ws
    network_mode: "host"
    command: tail -f /dev/null

volumes:
  ws:
